# Site settings
title: Micah Richey
email: email@email.com
description: > # this means to ignore newlines until "baseurl:"
  I am a graduate student, studying philosophy at the University of Rochester.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "mkrichey.github.io" # the base hostname & protocol for your site
twitter_username: micahkrichey
github_username:  mkrichey

# Build settings
markdown: kramdown
